// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package org.apache.doris.nereids.trees.expressions.functions.scalar;

import org.apache.doris.catalog.FunctionSignature;
import org.apache.doris.nereids.trees.expressions.Expression;
import org.apache.doris.nereids.trees.expressions.functions.ExplicitlyCastableSignature;
import org.apache.doris.nereids.trees.expressions.functions.PropagateNullable;
import org.apache.doris.nereids.trees.expressions.shape.UnaryExpression;
import org.apache.doris.nereids.trees.expressions.visitor.ExpressionVisitor;
import org.apache.doris.nereids.parser.Dialect;
import org.apache.doris.nereids.types.BigIntType;
import org.apache.doris.nereids.types.DecimalV3Type;
import org.apache.doris.nereids.types.DoubleType;
import org.apache.doris.qe.ConnectContext;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.List;

/**
 * ScalarFunction 'sign'. This class is generated by GenerateFunction.
 */
public class Sign extends ScalarFunction
        implements UnaryExpression, ExplicitlyCastableSignature, PropagateNullable {

    public static final List<FunctionSignature> SIGNATURES = ImmutableList.of(
            FunctionSignature.ret(BigIntType.INSTANCE).args(DoubleType.INSTANCE)
    );

    private static final List<FunctionSignature> ORACLE_SIGNATURES = ImmutableList.of(
            FunctionSignature.ret(DecimalV3Type.createDecimalV3Type(1, 0)).args(DecimalV3Type.WILDCARD)
    );

    /**
     * constructor with 1 argument.
     */
    public Sign(Expression arg) {
        super("sign", arg);
    }

    /** constructor for withChildren and reuse signature */
    private Sign(ScalarFunctionParams functionParams) {
        super(functionParams);
    }

    /**
     * withChildren.
     */
    @Override
    public Sign withChildren(List<Expression> children) {
        Preconditions.checkArgument(children.size() == 1);
        return new Sign(getFunctionParams(children));
    }

    @Override
    public List<FunctionSignature> getSignatures() {
        return isOracleDialect() && child().getDataType() instanceof DecimalV3Type
                ? ORACLE_SIGNATURES : SIGNATURES;
    }

    private boolean isOracleDialect() {
        return ConnectContext.get() != null
                && ConnectContext.get().getSessionVariable().getSqlParseDialect() == Dialect.ORACLE;
    }

    @Override
    public <R, C> R accept(ExpressionVisitor<R, C> visitor, C context) {
        return visitor.visitSign(this, context);
    }
}
