// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package org.apache.doris.nereids.trees.expressions.functions.scalar;

import org.apache.doris.catalog.FunctionSignature;
import org.apache.doris.catalog.Type;
import org.apache.doris.nereids.CascadesContext;
import org.apache.doris.nereids.parser.Dialect;
import org.apache.doris.nereids.rules.expression.ExpressionRewriteContext;
import org.apache.doris.nereids.rules.expression.rules.FoldConstantRuleOnFE;
import org.apache.doris.nereids.trees.expressions.Cast;
import org.apache.doris.nereids.trees.expressions.Expression;
import org.apache.doris.nereids.trees.expressions.functions.ComputePrecisionForRound;
import org.apache.doris.nereids.trees.expressions.functions.PropagateNullable;
import org.apache.doris.nereids.trees.expressions.functions.SearchSignatureForRound;
import org.apache.doris.nereids.trees.expressions.literal.IntegerLikeLiteral;
import org.apache.doris.nereids.trees.expressions.visitor.ExpressionVisitor;
import org.apache.doris.nereids.types.BigIntType;
import org.apache.doris.nereids.types.DateTimeV2Type;
import org.apache.doris.nereids.types.DecimalV3Type;
import org.apache.doris.nereids.types.DoubleType;
import org.apache.doris.nereids.types.FloatType;
import org.apache.doris.nereids.types.IntegerType;
import org.apache.doris.nereids.types.LargeIntType;
import org.apache.doris.nereids.types.SmallIntType;
import org.apache.doris.nereids.types.TinyIntType;
import org.apache.doris.nereids.types.VarcharType;
import org.apache.doris.nereids.types.coercion.Int32OrLessType;
import org.apache.doris.nereids.types.coercion.IntegralType;
import org.apache.doris.qe.ConnectContext;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.List;

/**
 * ScalarFunction 'truncate'. This class is generated by GenerateFunction.
 */
public class Truncate extends ScalarFunction
        implements SearchSignatureForRound, PropagateNullable, ComputePrecisionForRound {

    public static final List<FunctionSignature> SIGNATURES = ImmutableList.of(
            FunctionSignature.ret(DecimalV3Type.WILDCARD).args(DecimalV3Type.WILDCARD, IntegerType.INSTANCE),
            FunctionSignature.ret(DoubleType.INSTANCE).args(DoubleType.INSTANCE, IntegerType.INSTANCE),
            FunctionSignature.ret(DoubleType.INSTANCE).args(FloatType.INSTANCE, IntegerType.INSTANCE),
            FunctionSignature.ret(LargeIntType.INSTANCE).args(LargeIntType.INSTANCE, IntegerType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(BigIntType.INSTANCE, IntegerType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(IntegerType.INSTANCE, IntegerType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(SmallIntType.INSTANCE, IntegerType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(TinyIntType.INSTANCE, IntegerType.INSTANCE)
    );

    private static final List<FunctionSignature> ORACLE_EXTRA_SIGNATURES = ImmutableList.of(
            FunctionSignature.ret(DecimalV3Type.WILDCARD).args(DecimalV3Type.WILDCARD),
            FunctionSignature.ret(DoubleType.INSTANCE).args(DoubleType.INSTANCE),
            FunctionSignature.ret(DoubleType.INSTANCE).args(FloatType.INSTANCE),
            FunctionSignature.ret(LargeIntType.INSTANCE).args(LargeIntType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(BigIntType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(IntegerType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(SmallIntType.INSTANCE),
            FunctionSignature.ret(BigIntType.INSTANCE).args(TinyIntType.INSTANCE),
            FunctionSignature.ret(DateTimeV2Type.SYSTEM_DEFAULT).args(DateTimeV2Type.WILDCARD),
            FunctionSignature.ret(DateTimeV2Type.SYSTEM_DEFAULT)
                    .args(DateTimeV2Type.WILDCARD, VarcharType.SYSTEM_DEFAULT)
    );

    /**
     * constructor with 1 argument.
     */
    public Truncate(Expression arg0) {
        super("truncate", arg0);
    }

    /**
     * constructor with 2 arguments.
     */
    public Truncate(Expression arg0, Expression arg1) {
        super("truncate", arg0, arg1);
    }

    /** constructor for withChildren and reuse signature */
    private Truncate(ScalarFunctionParams functionParams) {
        super(functionParams);
    }

    /**
     * withChildren.
     */
    @Override
    public Truncate withChildren(List<Expression> children) {
        Preconditions.checkArgument(children.size() == 1 || children.size() == 2);
        return new Truncate(getFunctionParams(children));
    }

    @Override
    public List<FunctionSignature> getSignatures() {
        if (!isOracleDialect()) {
            return SIGNATURES;
        }
        return ImmutableList.<FunctionSignature>builder()
                .addAll(SIGNATURES)
                .addAll(ORACLE_EXTRA_SIGNATURES)
                .build();
    }

    @Override
    public FunctionSignature computeSignature(FunctionSignature signature) {
        FunctionSignature computedSignature = super.computeSignature(signature);
        if (getArgumentType(0) instanceof IntegralType
                && ((IntegralType) getArgumentType(0)).isUnsigned()
                && computedSignature.returnType instanceof IntegralType) {
            IntegralType returnType = (IntegralType) computedSignature.returnType;
            return computedSignature.withReturnType(
                    returnType.withTypeDescriptor(Type.TYPE_DESCRIPTOR_UNSIGNED_MASK));
        }
        return computedSignature;
    }

    @Override
    public FunctionSignature computePrecision(FunctionSignature signature) {
        if (!(signature.getArgType(0) instanceof DecimalV3Type)) {
            return signature;
        }
        DecimalV3Type inputType = DecimalV3Type.forType(getArgumentType(0));
        FunctionSignature computedSignature = signature.withArgumentType(0, inputType);
        if (isOracleDialect()) {
            return computedSignature.withReturnType(inputType);
        }

        Integer scale = getConstantScale();
        if (scale == null || scale >= inputType.getScale()) {
            return computedSignature.withReturnType(inputType);
        }

        int resultScale = Math.max(scale, 0);
        int resultPrecision = Math.max(1,
                inputType.getPrecision() - inputType.getScale() + resultScale);
        return computedSignature.withReturnType(
                DecimalV3Type.createDecimalV3Type(resultPrecision, resultScale));
    }

    private Integer getConstantScale() {
        Expression scaleArgument = getArgument(1);
        if (!scaleArgument.isLiteral() && !scaleArgument.isSlot()) {
            ExpressionRewriteContext rewriteContext = new ExpressionRewriteContext(
                    CascadesContext.initTempContext());
            scaleArgument = FoldConstantRuleOnFE.evaluate(scaleArgument, rewriteContext);
        }
        if (scaleArgument instanceof Cast) {
            Expression castChild = scaleArgument.child(0);
            if (castChild.isLiteral() && !castChild.isNullLiteral()
                    && castChild.getDataType() instanceof Int32OrLessType) {
                return ((IntegerLikeLiteral) castChild).getIntValue();
            }
        } else if (scaleArgument.isLiteral() && !scaleArgument.isNullLiteral()
                && scaleArgument.getDataType() instanceof Int32OrLessType) {
            return ((IntegerLikeLiteral) scaleArgument).getIntValue();
        }
        return null;
    }

    private boolean isOracleDialect() {
        return ConnectContext.get() != null
                && ConnectContext.get().getSessionVariable() != null
                && ConnectContext.get().getSessionVariable().getSqlParseDialect() == Dialect.ORACLE;
    }

    @Override
    public <R, C> R accept(ExpressionVisitor<R, C> visitor, C context) {
        return visitor.visitTruncate(this, context);
    }
}
